### ISSUE TITLE
Installation fails under Ubuntu 16.04

### ISSUE THREAD

**Issue by spekulatius** [vintagesucks/caddy-script#68]
Hello @vintagesucks 

I've tried to install Caddy on a Scaleway server and it failed. Below is the output. Maybe you got an idea where to look next?

    root@scw-803c89:~# bash <(curl -s https://raw.githubusercontent.com/vintagesucks/caddy-script/master/main.sh)
    
    Current default time zone: 'Europe/Berlin'
    Local time is now:      Mon May 28 15:41:03 CEST 2018.
    Universal Time is now:  Mon May 28 13:41:03 UTC 2018.
    
    Enter an email address (e.g. admin@example.org) xxxx@gmail.com
    Enter a domain (e.g. example.org) xxxxxxx.com
    Enter the Caddy extensions you want (e.g. http.git,http.upload) http.root,http.fastcgi,http.rewrite
    Install WordPress? (Y/N)n
    Install Shopware? (Y/N)n
    Install phpMyAdmin? (Y/N)n
    Configure unattended-upgrades? (Y/N)y
    - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
         Caddy Features: http.root,http.fastcgi,http.rewrite
                 Domain: xxxx.com
                  Email: xxxxx@gmail.com
              WordPress: 0
               Shopware: 0
             phpMyAdmin: 0
    unattended-upgrades: 1
    
    Continue with setup? (Y/N)y
    Checking if logged in user is root.
    User is root.
    Checking if user caddy already exists.
    Adding user caddy.
    Adding user `caddy' ...
    Adding new group `caddy' (1000) ...
    Adding new user `caddy' (1000) with group `caddy' ...
    Creating home directory `/home/caddy' ...
    Copying files from `/etc/skel' ...
    Adding user caddy to sudoers.
    Successfully set up user caddy and needed permissions.
    Installing Caddy.
    Downloading Caddy for linux/arm64 (personal license)...
    curl: (22) The requested URL returned error: 400 Bad Request
    Aborted, error 22 in command: curl -fsSL "$caddy_url" -u "$CADDY_ACCOUNT_ID:$CADDY_API_KEY" -o "$dl"

**Comment by vintagesucks** [comment]
Hello @spekulatius,

thank you for opening an issue! `http.root`, `http.fastcgi`, and `http.rewrite` are [Standard HTTP Directives](https://caddyserver.com/docs) and you ~don't have to~ cannot include them in your list of _extra_ features/plugins as they already ship with Caddy by default (hence the `400 Bad Request` error.)

Related: #62

Hope this helps!

**Comment by vintagesucks** [comment]
see #69
