### ISSUE TITLE
handle standard http directives

### ISSUE THREAD

**Issue by vintagesucks** [vintagesucks/caddy-script#69]
see #62, #68 

either ignore [them](https://caddyserver.com/docs) as they are installed anyway or print a helpful error message

**Comment by spekulatius** [comment]
If there aren't really needed I would put out a message and continue with ignoring it @vintagesucks ...

**Comment by vintagesucks** [comment]
The problem I see with this: I'd have to maintain a list of Standard HTTP Directives to ignore and strip them from the input, which is IMHO out of scope for this script.

I could probably add a troubleshooting section to the readme explaining why this is happening, but causing a bad request by providing invalid input as a parameter is to be expected.

The `Caddy extensions` input is meant for plugins (like the `Add plugins` section on https://caddyserver.com/download), not base directives of Caddy itself.

**Comment by vintagesucks** [comment]
@spekulatius FYI: Feel free to add your opinion on this, I only closed the issue to keep track of other issues that require my attention.

**Comment by spekulatius** [comment]
No problem for closing. 

I understand your reasoning on this. It always depends on what your focus is. Providing a simple helper script or a comprehensive install assistant... Totally up to you.

**Comment by vintagesucks** [comment]
I actually plan to do a rewrite of this script in the future which will be much closer to a comprehensive install assistant and handling the Standard Directives is likely to be a feature of that.

It's a good thing you opened the issue regarding this. As someone familiar with Caddy I never ran into this issue, but I can totally see how to miss this if you are not familiar with the software and just want an automated script to handle everything for you.

**Comment by spekulatius** [comment]
Cool. That would be awesome. You would make peoples lives a lot easier.
Setting caddy up isn't as straight forward as other software packages
unfortunately.

**Comment by vintagesucks** [comment]
Still an issue.
