### ISSUE TITLE
Using DigitalOcean Ubuntu Docker Image

### ISSUE THREAD

**Issue by joshuamallow** [vintagesucks/caddy-script#71]
Using a clean DigitalOcean Ubuntu/Docker droplet, I am having difficulty getting this to start.

It installs fine, but won't start. It is a clean droplet with ufw disabled, and no DigitalOcean firewall setup yet.

It is basically restarting until it hits the hourly LetsEncrypt rate limit. I've tried disabling the "Restart-on-failure", but it still won't start. Am I missing something really simple? No firewall. But it won't get a cert. It gives error 400 until it reaches the hourly limit then throws error 429 (rate limiting). 

Any thoughts?

**Comment by vintagesucks** [comment]
Hello @joshuamallow, thank you for opening an issue! 

Just to clarify: Did you try to run caddy-script inside of Docker? It's not really intended or tested to be used in this way. Could you provide instructions on how you set up your Docker Droplet and the steps you took to install caddy-script so I can try to reproduce and investigate your issue?

**Comment by ambient-home-systems** [comment]
No, I am not trying to run the caddy-script within Docker.

Steps to recreate:
1. On DigitalOcean, I create a brand new droplet ($5, 1GB 1vCPU) using the "Ubuntu 16.04 with Docker 17.12" image.
2. Login, run apt-get update, apt-get upgrade. Disable UFW firewall.
3. Run the caddy-script from SSH.

I'm installing it on an essentially brand new system. It seems like there is a firewall issue, but I disable UFW and the DigitalOcean cloud firewall isn't enabled yet either.

**Comment by vintagesucks** [comment]
Sorry, but I am unable to reproduce your issue. Here are the steps I took:

![grafik](https://user-images.githubusercontent.com/13335308/42245132-ed56cef8-7f17-11e8-83e8-8c74ec4b3bb7.png)

`root@docker-s-1vcpu-1gb-fra1-01:~# apt-get update`
`root@docker-s-1vcpu-1gb-fra1-01:~# apt-get upgrade`
`root@docker-s-1vcpu-1gb-fra1-01:~# sudo ufw disable`

```
root@docker-s-1vcpu-1gb-fra1-01:~# bash <(curl -s https://raw.githubusercontent.com/vintagesucks/caddy-script/master/main.sh)

Current default time zone: 'Europe/Berlin'
Local time is now:      Tue Jul  3 23:14:50 CEST 2018.
Universal Time is now:  Tue Jul  3 21:14:50 UTC 2018.

Enter an email address (e.g. admin@example.org) [removed]
Enter a domain (e.g. example.org) 71.nikol.as
Enter the Caddy extensions you want (e.g. http.git,http.upload)
Are you sure you want to continue without additional Caddy features? (Y/N)y
Install WordPress? (Y/N)n
Install Shopware? (Y/N)n
Install phpMyAdmin? (Y/N)n
Configure unattended-upgrades? (Y/N)n
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
     Caddy Features:
             Domain: 71.nikol.as
              Email: [removed]
          WordPress: 0
           Shopware: 0
         phpMyAdmin: 0
unattended-upgrades: 0
```

As you can see ~on [https://71.nikol.as](https://71.nikol.as/)~, everything went fine.

![grafik](https://user-images.githubusercontent.com/13335308/42893477-b7b8a49e-8ab4-11e8-9b9f-979784971653.png)

Are you sure that you pointed your domain to your droplet?

![grafik](https://user-images.githubusercontent.com/13335308/42245379-e62c735c-7f18-11e8-8572-81f4a9a58f4a.png)

**Comment by vintagesucks** [comment]
This issue has been closed because there has been no response to my request for more information from the original author. With only the information that is currently in the issue, I don't have enough information to take action. Please reach out if you have or find the answers I need so that I can investigate further.
