### ISSUE TITLE
Issue with WSL

### ISSUE THREAD

**Issue by Merith-TK** [vintagesucks/caddy-script#79]
When i run the intaller on my WSL (Ubuntu 16.04) it gives me this when running as root

```bash
bunny@DESKTOP-EHL74VA:~$ sudo bash <(curl -s https://raw.githubusercontent.com/vintagesucks/caddy-script/master/main.sh)
[sudo] password for bunny:
bash: /dev/fd/63: No such file or directory```

**Comment by vintagesucks** [comment]
Hello @DovaMerith, thanks for opening an issue!

WSL is not supportet yet (see #5). I reopened the issue but I can't guarantee support or give an ETA. If WSL can be supported I'll implement it probably only after my [planned rewrite](https://github.com/vintagesucks/caddy-script/issues/69#issuecomment-393650807).

I'll close this issue, but feel free to add your opinion.

**Comment by Merith-TK** [comment]
i have found that this issue occasionally occures when traces of caddy still exist in the system after attempting to purge all caddy files.

even on a normal ubuntu install
