### ISSUE TITLE
[Shopware 5] Media Optimizer

### ISSUE THREAD

**Issue by vintagesucks** [vintagesucks/caddy-script#92]
![grafik](https://user-images.githubusercontent.com/13335308/64694265-97994580-d499-11e9-839c-3a81e82ac5ef.png)

Install at least one optimizer for each supported mimetype.

**Comment by arosenhagen** [comment]
be aware that this might be a display issue in the backend. We had this too although optimizers were available. see [https://gist.github.com/arosenhagen/ab583947c60133b4b39bfbd6d4cda369](https://gist.github.com/arosenhagen/ab583947c60133b4b39bfbd6d4cda369) for a patch which points them to the correct programs.
